import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from "@/src/lib/auth-store";
import { Topbar } from "@/src/components/topbar";
import { wireAuthAccessors } from "@/src/lib/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Shell = ({ children }: { children: React.ReactNode }) => {
    const { state, clear } = useAuth();
    wireAuthAccessors(() => state.accessToken, clear);
    return (
      <div className="min-h-screen flex flex-col">
        <Topbar onLogout={clear} />
        <div className="flex-1 grid grid-cols-[16rem_1fr]">
          {/* sidebar slot is per-page */}
          {children}
        </div>
      </div>
    );
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Shell>{children}</Shell>
        </AuthProvider>
      </body>
    </html>
  );
}
